export const business = {
  name: "Midyaji Basha",
  nameAr: "ميديجي باشا",
  category: "Turkish Street Food Restaurant",
  coreEntity: "Mussels",
  coreEntityAr: "المحار",
  phoneLocal: "0777774497",
  phoneIntl: "+962777774497",
  email: "info@midyajibasha.com",
  url: "https://midyajibasha.com",
  logo: "https://midyajibasha.com/logo.png",
  ogImage: "https://midyajibasha.com/og-image.jpg",
  targetCountry: "Jordan",
  targetCity: "Amman",
  cuisine: ["Turkish", "Turkish Street Food", "Seafood"],
  priceRange: "$$",
  menuUrl: "https://midyajibasha.com/en/menu",
  mapUrl: "https://maps.app.goo.gl/rXAR7u6CnJhJv7tk6",
  // A simple, reliable embed URL using coordinates (replace with an official place embed if you have one)
  mapEmbedUrl: `https://maps.google.com/maps?q=${31.9522},${35.9106}&z=17&output=embed`,
  sameAs: [
    "https://www.instagram.com/midyaji.basha",
    "https://web.facebook.com/midyajibasha",
    "https://www.youtube.com/@MidyajiBasha",
    "https://maps.app.goo.gl/rXAR7u6CnJhJv7tk6",
  ],
  address: {
    street: "Mecca Mall, 2nd Floor",
    city: "Amman",
    region: "Amman",
    postalCode: "11118",
    country: "Jordan",
  },
  latitude: 31.9522,
  longitude: 35.9106,
  openingHours: [
    { day: "Monday", opens: "10:00", closes: "22:00" },
    { day: "Tuesday", opens: "10:00", closes: "22:00" },
    { day: "Wednesday", opens: "10:00", closes: "22:00" },
    { day: "Thursday", opens: "10:00", closes: "22:00" },
    { day: "Friday", opens: "10:00", closes: "22:00" },
    { day: "Saturday", opens: "10:00", closes: "22:00" },
    { day: "Sunday", opens: "10:00", closes: "22:00" },
  ],
  currenciesAccepted: "JOD",
  paymentAccepted: "Cash, Credit Card, Mobile Payment",
};

export const seoKeywords = [
  "mussels Amman",
  "المحار عمان",
  "Midye Dolma Jordan",
  "Turkish stuffed mussels",
  "Turkish street food Amman",
  "Fatteh Yalanji",
  "Çiğ Köfte",
  "Turkish cuisine Jordan",
  "seafood culture",
  "Midyaji Basha",
];
